# This file will start a PostgreSQL database container and a pgAdmin container,
# but will not pull anything for the app itself. It also doesn't set up any volumes.
services:
  db:
    container_name: pocketbook_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pocketbook
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  