name: Build and Deploy

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build_image_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: binderlab/pocketbook
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Start Deployment
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.DEPLOY_HOST }}
          ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
          stack_file_name: docker-compose.yml
          docker_login_password: ${{ secrets.DOCKERHUB_TOKEN }}
          docker_login_user: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_login_registry : ${{ steps.login-action.outputs.registry }}
          args: -p pocketbook up -d
